#!/bin/bash
# One-shot setup for a fresh Linux (GPU) machine — RunPod-style.
#
#   git clone https://github.com/sleepmastergx/Context-WAM.git
#   cd Context-WAM && bash setup.sh && source env.sh
#   python train.py --arm control          # then: --arm ttt
#
# Knobs (env vars):
#   WORKSPACE    where data/checkpoints/outputs/hf live
#                (default: /workspace if writable — RunPod's volume — else ./workspace)
#   SKIP_VENV=1  install into the CURRENT python (e.g. a docker image's) instead
#                of creating $WORKSPACE/venv
#   SKIP_DATA=1  skip the dataset download (it needs HF credentials)
#   TORCH_INDEX  torch wheel index (default cu128, the build this was developed on)
#   HF_TOKEN     token with read access to the private dataset repo
#
# What it does: staged dependency install (torch FIRST — DeepSpeed's build
# imports it), directories under $WORKSPACE, env.sh with the exports every
# later shell needs, optional dataset download, then the CPU gates + loop
# smokes as verification. No GPU is required by setup itself.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)

if [ -z "${WORKSPACE:-}" ]; then
    if [ -d /workspace ] && [ -w /workspace ]; then WORKSPACE=/workspace
    else WORKSPACE=$HERE/workspace; fi
fi
mkdir -p "$WORKSPACE"/data "$WORKSPACE"/checkpoints "$WORKSPACE"/outputs "$WORKSPACE"/hf
echo "== WORKSPACE=$WORKSPACE"

# ---- python ----------------------------------------------------------------
PYBIN=$(command -v python3)
if [ "${SKIP_VENV:-0}" != "1" ]; then
    "$PYBIN" -m venv "$WORKSPACE/venv"
    PYBIN="$WORKSPACE/venv/bin/python"
fi
export PYTHONNOUSERSITE=1
"$PYBIN" -m pip install -q -U pip wheel setuptools
echo "== python: $("$PYBIN" -V) at $PYBIN"

# ---- dependencies, in the ONE order that works from scratch ----------------
# 1. torch first: DeepSpeed's setup imports it at build time.
TORCH_INDEX=${TORCH_INDEX:-https://download.pytorch.org/whl/cu128}
"$PYBIN" -m pip install "torch==2.7.1" "torchvision==0.22.1" --index-url "$TORCH_INDEX"
# 2. DeepSpeed without build isolation so its build env SEES torch.
"$PYBIN" -m pip install "deepspeed==0.18.5" --no-build-isolation
# 3. everything else (torch already satisfied, so nothing gets downgraded).
"$PYBIN" -m pip install -r "$HERE/requirements.txt"
# 4. vendored Fast-WAM with --no-deps: its pyproject pins exact "+cu128" local
#    versions that pip cannot resolve from PyPI; its real deps are in
#    requirements.txt instead.
"$PYBIN" -m pip install -e "$HERE/third_party/fastwam" --no-deps

# ---- paths -----------------------------------------------------------------
# Wan weights resolve to ./checkpoints RELATIVE TO CWD in the Fast-WAM loader;
# keep them on the volume via a symlink at the repo root.
ln -sfn "$WORKSPACE/checkpoints" "$HERE/checkpoints"

cat > "$HERE/env.sh" <<EOF
# generated by setup.sh — source this in every new shell
export PYTHONNOUSERSITE=1
export HF_HOME="$WORKSPACE/hf"
export CACHE_DIR="$WORKSPACE/data/movecube_fastwam"
export OUT_ROOT="$WORKSPACE/outputs"
EOF
if [ "${SKIP_VENV:-0}" != "1" ]; then
    echo "export PATH=\"$WORKSPACE/venv/bin:\$PATH\"" >> "$HERE/env.sh"
fi
# shellcheck disable=SC1091
source "$HERE/env.sh"

# ---- dataset (private HF repo) ---------------------------------------------
if [ "${SKIP_DATA:-0}" != "1" ]; then
    if "$PYBIN" - <<'EOF'
from huggingface_hub import HfApi
import sys
try:
    HfApi().whoami()
except Exception:
    sys.exit(1)
EOF
    then
        "$PYBIN" "$HERE/scripts/download_data.py" --out "$CACHE_DIR"
    else
        echo "== NOTE: no HF credentials found — skipping the 3.7 GiB download."
        echo "   export HF_TOKEN=<token with access to SleepMastger/movecube-fastwam-cache>"
        echo "   (or huggingface-cli login), then:"
        echo "   python scripts/download_data.py --out \$CACHE_DIR"
    fi
fi

# ---- verification: CPU gates + loop smokes (~2 min, no GPU needed) ---------
cd "$HERE"
"$PYBIN" checks/check_sliding_chain.py
"$PYBIN" checks/check_arms_match.py
"$PYBIN" checks/check_write_once.py
"$PYBIN" train.py --arm control --synthetic --steps 2 --out "$WORKSPACE/outputs/smoke_control"
"$PYBIN" train.py --arm ttt     --synthetic --steps 2 --out "$WORKSPACE/outputs/smoke_ttt"

echo
echo "== setup complete. Every new shell:  source env.sh"
echo "== single GPU :  python train.py --arm control     (then --arm ttt)"
echo "== multi GPU  :  bash scripts/launch_control.sh    (then launch_ttt.sh)"
echo "== first real run downloads the Wan2.2 weights into ./checkpoints -> \$WORKSPACE/checkpoints"
